apiVersion: v1
kind: Service
metadata:
  labels:
    run: hello-world
  name: hello-world
spec:
  ports:
  - nodePort: 31000
    port: 1080
    targetPort: 1080
  selector:
    run: hello-world
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello-world
  name: hello-world
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-world
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
      - image: hello-world:%VERSION%
        imagePullPolicy: Always
        name: hello-world
        ports:
        - containerPort: 1080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 125m
            memory: 125Mi